/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/shadedHead/model.glb 
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

export function Head3D(props: any) {
  const { nodes, materials } = useGLTF("/models/shadedHead/model.glb ");

  const insideMaterial = new THREE.MeshStandardMaterial({
    color: 0x9ffaff,
    side: THREE.BackSide,
  })
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.model.geometry}
        material={materials.CustomMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      />
            <mesh
        geometry={nodes.model.geometry}
        material={insideMaterial}
        rotation={[Math.PI / 2, 0, 0]}
        // scale={[0.9, 0.9, 0.9]} // Slightly larger to avoid z-fighting
      />
      {/* <mesh
        geometry={nodes.model.geometry}
        material={blackMaterial}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.6, 0.6, 0.6]}
      /> */}
    </group>
  );
}

useGLTF.preload("/models/shadedHead/model.glb ");
